### ISSUE TITLE
Could it be that the serif theme contains code that could be considered malware by google ads?

### ISSUE THREAD

**Issue by ulimaps** [JugglerX/hugo-serif-theme#30]
Hi. I'm using the serif theme, which I think is great, but when I try to use google ads, it tells me that my site (geoytopo.com) contains code that could be considered malware. 
Question: would there be any code inside the public folder that you consider could be warned as malware? It's a respectful question, I honestly don't know about programming, but I want to be able to use the google ads with the serif theme.

Best regards

**Comment by JugglerX** [comment]
There is no Malware in the theme. 

I'm not sure what's triggering this warning, maybe your sites host has malware, or you've installed some 3rd party tracking code. 

I know that when I click a Google ad my ad blocker shows a warning, but this happens because I'm clicking an ad, it's nothing to do with the websites.

**Comment by ulimaps** [comment]
Thank you very much for your reply. So the malware problem I have may be due to another reason. I will look for help in the hosting service and with google.
I think you can finish this issue.

I am very grateful for your kind response.
